# Generated by Django 5.0.7 on 2024-08-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
